name: Generate Allure Report and Email

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest allure-pytest  # Add pytest-allure-adaptor if needed

      - name: Run tests
        run: |
          pytest tests/ --alluredir=allure-results
        continue-on-error: false  # Fail the job if tests fail

      - name: Install Allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.25.0/allure-2.25.0.zip
          unzip allure-2.25.0.zip
          sudo mv allure-2.25.0 /opt/allure
          echo "/opt/allure/bin" >> $GITHUB_PATH

      - name: Generate Allure report
        run: |
          allure generate allure-results -o allure-report --clean
        if: always()

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

      - name: Set up email environment
        run: |
          echo "GITHUB_REPOSITORY=${{ github.repository }}" >> $GITHUB_ENV
          echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV

      - name: Send email
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          MANAGER_EMAIL: ${{ secrets.MANAGER_EMAIL }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          python send_email.py
